### ISSUE TITLE
Internal Server Error 500(/profile)

### ISSUE THREAD

**Issue by dharshan-kumarj** [sanjaysagar12/RestAPI-Automation-Backend#3]
Internal Server Error 500  in  /profile
![Screenshot from 2024-05-30 17-49-40](https://github.com/sanjaysagar12/RestAPI-Automation-Backend/assets/155003114/75a2f053-0f9c-48f4-99ae-ad6abcbec614)

**Comment by sanjaysagar12** [comment]
Fixed Internal Server Error 500(/profile) 7e332ff387f55903afc9bea76fc75421a67fc7f3
